packages:
  - "apps/*"
  - "packages/*"
verifyDepsBeforeRun: false
onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - lightningcss
  - prisma
  - sharp
  - unrs-resolver
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
