// SPDX-License-Identifier: AGPL-3.0-or-later
import crypto from "node:crypto";

/**
 * Bundle signature verification.
 *
 * Knowledge bundles are signed offline with an ed25519 private key. The
 * matching public key is supplied via PRINCIPE_UPDATES_PUBLIC_KEY (env)
 * or falls back to the project default constant below — which Omer
 * publishes alongside each release and contributors can pin in their
 * own builds.
 *
 * Rotation: publisher generates a new ed25519 keypair, the new public
 * key ships in the next release's PRINCIPE_UPDATES_PUBLIC_KEY default.
 * Self-hosters can override via env to trust their own publisher key.
 */

// Project default — overrideable via env. Hex-encoded ed25519 public key
// (32 bytes = 64 hex chars). The constant below is a placeholder pending
// the real publisher key being generated by Omer. Treat as untrusted
// until you've matched it against a fingerprint published outside the
// repo (security@principe.cloud, future GPG-signed announcement, etc.).
const DEFAULT_PUBLIC_KEY_HEX =
  "0000000000000000000000000000000000000000000000000000000000000000";

export class InvalidSignatureError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InvalidSignatureError";
  }
}

export class InvalidPublicKeyError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InvalidPublicKeyError";
  }
}

/**
 * Returns the configured ed25519 public key as a Node KeyObject suitable
 * for crypto.verify(). Throws InvalidPublicKeyError if the configured
 * key isn't 32 bytes of hex.
 */
export function getUpdatesPublicKey(): crypto.KeyObject {
  const hex = (
    process.env.PRINCIPE_UPDATES_PUBLIC_KEY ?? DEFAULT_PUBLIC_KEY_HEX
  ).trim();
  if (!/^[0-9a-fA-F]{64}$/.test(hex)) {
    throw new InvalidPublicKeyError(
      `PRINCIPE_UPDATES_PUBLIC_KEY must be 32 bytes hex (64 chars); got ${hex.length}.`,
    );
  }
  const raw = Buffer.from(hex, "hex");
  // ed25519 public key in raw form (32 bytes). createPublicKey wants a
  // DER-encoded SPKI, so wrap the raw key with the standard prefix.
  const spki = Buffer.concat([
    Buffer.from("302a300506032b6570032100", "hex"),
    raw,
  ]);
  return crypto.createPublicKey({ key: spki, format: "der", type: "spki" });
}

/**
 * Verify a detached ed25519 signature over manifest bytes.
 *
 * @param manifestBytes  raw bytes of manifest.json
 * @param signatureBytes raw 64-byte ed25519 signature
 * @returns true if valid, throws InvalidSignatureError if not
 */
export function verifyManifestSignature(
  manifestBytes: Buffer,
  signatureBytes: Buffer,
): boolean {
  if (signatureBytes.length !== 64) {
    throw new InvalidSignatureError(
      `ed25519 signatures must be 64 bytes; got ${signatureBytes.length}.`,
    );
  }
  const ok = crypto.verify(
    null, // ed25519 takes no hash algorithm
    manifestBytes,
    getUpdatesPublicKey(),
    signatureBytes,
  );
  if (!ok) {
    throw new InvalidSignatureError(
      "Manifest signature did not verify against the configured public key.",
    );
  }
  return true;
}

/**
 * SHA-256 of a buffer, hex-encoded. Used to verify bundle integrity
 * after the manifest signature passes — the manifest commits to the
 * bundle's sha256, and we hash the downloaded tarball to confirm match.
 */
export function sha256Hex(bytes: Buffer): string {
  return crypto.createHash("sha256").update(bytes).digest("hex");
}
